### ISSUE TITLE
use mediawiki install path and URL

### ISSUE THREAD

**Issue by guaka** [Trustroots/mediawiki-nostr-auth#19]
`includes/Special/auth.js` and `includes/Special/content.php` should use URL and script path vars, probably `$wgScriptPath` and `$wgServer`

at least here:
```
var WIKIURL = "https://nomadwiki.org";
var ENDPOINT = WIKIURL + "/api.php";
```

**Comment by guaka** [comment]
this is better, but probably needs to be inside something like `$(document).ready(function() {`

```
var WIKIURL = mw.config.get('wgServer');
var ENDPOINT = WIKIURL + mw.config.get('wgScriptPath') + "/api.php";
```

**Comment by tillwenke** [comment]
Done
