### ISSUE TITLE
Link in top right

### ISSUE THREAD

**Issue by guaka** [Trustroots/mediawiki-nostr-auth#22]
Would be nice to have a link to nostr login in the top right, next to the login link.

I've used the MediaWiki OpenID extension a lot in the past, it adds a link in the top right.
https://www.mediawiki.org/wiki/Extension:OpenID_Connect

For now I added a link at https://nomadwiki.org/en/MediaWiki:Sidebar

**Comment by tillwenke** [comment]
done
